ex_compile:
	gcc `pkg-config --cflags glib-2.0` ex_compile.c `pkg-config --libs glib-2.0` -o ex_compile.o

word_count:
	gcc `pkg-config --cflags glib-2.0` word_count.c `pkg-config --libs glib-2.0` -o word_count.o
